import type { DocumentRecord } from './api';
import type { StoredChunk } from './chunks';

/** Build task narrative from room evidence. */
export function synthesizeTaskOutput(title: string, docs: DocumentRecord[], chunks: StoredChunk[]): string {
  const verified = docs.filter(d => d.verified);
  const sources = verified.map(d => d.name).join(', ') || 'no verified sources';
  const passages = (chunks.length
    ? chunks.slice(0, 4).map(c => c.text)
    : verified.map(d => d.sourceText || '').filter(Boolean)
  ).slice(0, 4);

  const body = passages.map((p, i) => `(${i + 1}) ${p.slice(0, 280)}`).join('\n\n');

  switch (title) {
    case 'Summarization':
      return `## Executive Summary\nSources: ${sources}\n\n${body || 'Insufficient source text.'}\n\n— Generated by ProofEngine v2`;
    case 'Q&A Across Docs':
      return `## Cross-document Q&A brief\nIndexed ${verified.length} verified docs.\n\nKey passages:\n${body || '—'}\n\n— ProofEngine v2`;
    case 'Data Extraction':
      return `## Extracted metrics & clauses\nFrom: ${sources}\n\n${body || 'No structured fields found in excerpts.'}\n\n— ProofEngine v2`;
    case 'Red-Flag Detection':
      return `## Red-flag scan\nScope: ${sources}\n\nRisk language / issues surfaced:\n${body || 'No high-risk language in available excerpts.'}\n\n— ProofEngine v2`;
    case 'Memo Drafting':
    case 'Client Memo Draft':
      return `## Client memo (draft)\nTo: Stakeholders\nRe: ${sources}\n\nFindings:\n${body || 'Pending source verification.'}\n\nNext steps: confirm approval gate, publish microsite.\n\n— ProofEngine v2`;
    default:
      return `## ${title}\nSources: ${sources}\n\n${body}\n\n— ProofEngine v2`;
  }
}
